import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Contact Page",
  description: "Generated by create next app",
  keywords: ["Contact Page", "Generated by create next app"],
};
export default function ContactPage() {
  return (
    <>
      <span className="text-7xl">Contact Page</span>
    </>
  );
}
